name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  CD:
    name: Continuous Deployment
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
